export const availableTags = [
  "Action",
  "Adventure",
  "Fantasy",
  "Sci-Fi",
  "Romance",
  "Mystery",
  "Thriller", 
  "Horror", 
  "Comedy",
  "Drama",
  "Young Adult", 
  "Historical", 
  "Dystopian",
  "Crime", 
  "Supernatural",
  "Philosophical",
  "Slice of Life",
  "Bildungsroman", 
  "Classic",
  "Contemporary",
  "Family Saga",
  "Friendship",
  "Humor",
  "Inspirational",
  "Literary",
  "Magic",
  "Mythology",
  "Paranormal",
  "Quirky",
  "Realistic",
  "Satire",
  "Short Stories",
  "Sports",
  "Suspense",
  "Travel",
  "Uplifting",
  "Urban", 
  "Western",
  "World Building", 
  "Ancient History",
  "Medieval",
  "Victorian",
  "Futuristic",
  "Post Apocalyptic",
  "Space",
  "Rural",
  "Small Town",
  "School Life",
  "Fantasy World", 
  "Alternate Reality",
  "Multiverse",
  "Animals", 
  "Heroes",
  "Villains",
  "Friendship",
  "Family",
  "Coming-of-Age",
  "Protagonist Driven",
  "Character Study",
  "Fast-Paced",
  "Slow Burn",
  "Plot Twist",
  "Intrigue",
  "Quest",
  "Survival",
  "Conspiracy",
  "Investigation",
  "Transformation",
  "Self-Discovery",
  "Whimsical",
  "Dark", 
  "Lighthearted",
  "Emotional",
  "Thought-Provoking",
  "Cozy", 
  "Heartwarming",
  "Intense",
  "Aliens",
  "Artificial Intelligence (AI)",
  "Robots",
  "Time Travel",
  "Magic System",
  "Monsters",
  "Vampires", 
  "Werewolves",
  "Ghosts",
  "Witches",
  "Dragons",
  "Fae", 
  "Gods & Goddesses",
  "Parallel Worlds",
  "Superpowers",
  "Mythical Creatures",
  "Secret Societies",
  "Heist",
  "War", 
  "Moral Dilemmas",
  "Middle Grade", 
  "New Adult", 
];

export const novelGenres = [
  "Action",
  "Adventure",
  "Alternate History",
  "Biopunk",
  "Chick Lit",
  "Children's Fiction",
  "Classic",
  "Comedy",
  "Coming-of-Age",
  "Contemporary Fiction",
  "Cozy Mystery",
  "Crime",
  "Cyberpunk",
  "Dark Fantasy",
  "Detective",
  "Dystopian",
  "Erotic Romance",
  "Espionage",
  "Fantasy",
  "General Fiction",
  "Gothic",
  "Grimdark Fantasy",
  "Hard Sci-Fi",
  "Historical Fiction",
  "Historical Fantasy",
  "Historical Romance",
  "Horror",
  "Humor",
  "LGBTQ+ Fiction",
  "Literary Fiction",
  "Magical Realism",
  "Medical Thriller",
  "Military Sci-Fi",
  "Mystery",
  "Mythic Fantasy",
  "New Adult",
  "Noir",
  "Paranormal",
  "Paranormal Romance",
  "Philosophical Fiction",
  "Poetry",
  "Political Thriller",
  "Portal Fantasy",
  "Post-Apocalyptic",
  "Psychological Thriller",
  "Realistic Fiction",
  "Romance",
  "Romantic Comedy",
  "Satire",
  "Science Fiction",
  "Short Stories",
  "Slice of Life",
  "Soft Sci-Fi",
  "Space Opera",
  "Steampunk",
  "Supernatural",
  "Suspense",
  "Techno-Thriller",
  "Thriller",
  "Time Travel",
  "Tragedy",
  "Urban Fantasy",
  "Upmarket Fiction",
  "Western",
  "Young Adult (YA)",
  "Young Adult Fantasy",
  "Young Adult Romance",
];
